"""Schema definitions for document data."""

from __future__ import annotations

import pandera.pandas as pa

DocumentsSchema: pa.DataFrameSchema = pa.DataFrameSchema(
    {
        "document_chembl_id": pa.Column(str, required=True),
        "doi": pa.Column(str, required=False),
        "title": pa.Column(str, required=False),
        "Index": pa.Column(str, required=False),
        "OpenAlex.Error": pa.Column(str, required=False),
        "OpenAlex.Genre": pa.Column(str, required=False),
        "OpenAlex.Id": pa.Column(str, required=False),
        "OpenAlex.MeshDescriptors": pa.Column(str, required=False),
        "OpenAlex.MeshQualifiers": pa.Column(str, required=False),
        "OpenAlex.TypeCrossref": pa.Column(str, required=False),
        "OpenAlex.Venue": pa.Column(str, required=False),
        "OpenAlex.is_review": pa.Column(str, required=False),
        "PubMed.Abstract": pa.Column(str, required=False),
        "PubMed.ArticleTitle": pa.Column(str, required=False),
        "PubMed.ChemicalList": pa.Column(str, required=False),
        "PubMed.DOI": pa.Column(str, required=False),
        "PubMed.DayCompleted": pa.Column(str, required=False),
        "PubMed.DayRevised": pa.Column(str, required=False),
        "PubMed.EndPage": pa.Column(str, required=False),
        "PubMed.Error": pa.Column(str, required=False),
        "PubMed.ISSN": pa.Column(str, required=False),
        "PubMed.Issue": pa.Column(str, required=False),
        "PubMed.JournalTitle": pa.Column(str, required=False),
        "PubMed.MeSH_Descriptors": pa.Column(str, required=False),
        "PubMed.MeSH_Qualifiers": pa.Column(str, required=False),
        "PubMed.MonthCompleted": pa.Column(str, required=False),
        "PubMed.MonthRevised": pa.Column(str, required=False),
        "PubMed.PMID": pa.Column(str, required=False),
        "PubMed.StartPage": pa.Column(str, required=False),
        "PubMed.Volume": pa.Column(str, required=False),
        "PubMed.YearCompleted": pa.Column(str, required=False),
        "PubMed.YearRevised": pa.Column(str, required=False),
        "PubMed.is_review": pa.Column(str, required=False),
        "abstract": pa.Column(str, required=False),
        "authors": pa.Column(str, required=False),
        "crossref.Error": pa.Column(str, required=False),
        "crossref.Subject": pa.Column(str, required=False),
        "crossref.Subtitle": pa.Column(str, required=False),
        "crossref.Subtype": pa.Column(str, required=False),
        "crossref.Title": pa.Column(str, required=False),
        "crossref.Type": pa.Column(str, required=False),
        "date_code": pa.Column(str, required=False),
        "first_page": pa.Column(str, required=False),
        "issue": pa.Column(str, required=False),
        "journal": pa.Column(str, required=False),
        "journal_abbrev": pa.Column(str, required=False),
        "last_page": pa.Column(str, required=False),
        "pubmed_id": pa.Column(str, required=False),
        "scholar.DOI": pa.Column(str, required=False),
        "scholar.Error": pa.Column(str, required=False),
        "scholar.ExternalIds": pa.Column(str, required=False),
        "scholar.PMID": pa.Column(str, required=False),
        "scholar.SemanticScholarId": pa.Column(str, required=False),
        "scholar.Venue": pa.Column(str, required=False),
        "scholar.is_review": pa.Column(str, required=False),
        "source": pa.Column(str, required=False),
        "volume": pa.Column(str, required=False),

    }
)

"""pa.DataFrameSchema: Validation schema for documents."""
