#!/usr/bin/env python3
"""Ensure pip-compile lock files were generated with the supported Python version."""

from __future__ import annotations

import pathlib
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
PYTHON_VERSION_FILE = REPO_ROOT / ".python-version"
REQUIREMENTS_LOCK = REPO_ROOT / "requirements-lock.txt"


class VersionError(RuntimeError):
    """Raised when lock files are generated with an unsupported Python version."""


def _read_expected_version() -> str:
    if PYTHON_VERSION_FILE.exists():
        expected = PYTHON_VERSION_FILE.read_text(encoding="utf-8").strip()
        if expected:
            return expected
    raise VersionError(
        "Expected to find a non-empty .python-version file specifying the supported Python version"
    )


def _extract_version_from_lock() -> str:
    if not REQUIREMENTS_LOCK.exists():
        raise VersionError(
            f"Could not find requirements lock file at {REQUIREMENTS_LOCK.relative_to(REPO_ROOT)}"
        )

    for line in REQUIREMENTS_LOCK.read_text(encoding="utf-8").splitlines():
        prefix = "# This file is autogenerated by pip-compile with Python "
        if line.startswith(prefix):
            return line.removeprefix(prefix).strip()

    raise VersionError(
        "Unable to determine pip-compile Python version from requirements-lock.txt header"
    )


def main() -> int:
    try:
        expected_version = _read_expected_version()
        actual_version = _extract_version_from_lock()
    except VersionError as exc:
        print(str(exc), file=sys.stderr)
        return 1

    expected_prefix = ".".join(expected_version.split(".")[:2])
    actual_prefix = ".".join(actual_version.split(".")[:2])

    if actual_prefix != expected_prefix:
        print(
            "requirements-lock.txt was generated with Python {actual}, expected {expected}".format(
                actual=actual_version,
                expected=expected_version,
            ),
            file=sys.stderr,
        )
        return 1

    print(
        "requirements-lock.txt header indicates pip-compile used Python {version}".format(
            version=actual_version,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
